#
# Copyright (c) 2019-2020 Oracle and/or its affiliates. All rights reserved.
#


title: Oracle Enterprise Manager 13c
description: Complete, Integrated, and Business-driven Enterprise Cloud Management solution
schemaVersion: 1.1.0
version: "20230524"
locale: "en"


# Support both single VM (EM/DB) as well as multi VM (HA + OCI DB)
variableGroups:
- title: "Configuration Details"
  variables:
  - zone_dns
  - cluster_name



# primaryOutputButton is a reference to a link output that creates a primary button
# on the Application Information tab.
# (Optional) if not provided, no primary button is shown.  Also if the output
# referenced is not a link output, no button is shown.
#primaryOutputButton: ${emconsole_url}
